### ISSUE TITLE
画图过程中line出现如图问题，如否是chinaprov40_line_coord文档的问题呢？

### ISSUE THREAD

**Issue by pkmyang** [r-stata/stata-prov-map#1]
![image](https://user-images.githubusercontent.com/71012219/129229991-a9300e0b-746f-48de-8d58-988593709f9f.png)
您好！按照作者提供的代码和文档运行后都出现了如图的边的问题，替换了三个chinaprov40_line_coord后都是这样，请问可以如何解决呢？谢谢！

**Comment by r-stata** [comment]
这个是因为你使用了 Stata16.0 ，这个版本的画地图就会出现这个问题，可以使用其他版本的，例如 16.1 和 15、14这些

**Comment by pkmyang** [comment]
使用了stata15就正常运行了，谢谢！
